server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: lab-conta-corrente
  datasource:
    url: jdbc:h2:mem:lab_account;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true



lab:
  account:
    exceptions:
      account-dont-exists-message: "Conta não encontrada."
      account-dont-exists-description: "Não foi possível encontrar a conta corrente informada."
      account-without-balance-message: "Saldo insuficiente."
      account-without-balance-description: "Não foi possível efetuar o débito, o saldo da conta informada é insuficiente."