apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:

        - name: account
          image: rafaelnicoleti/hexagonal-java-account:latest
          ports:
            - containerPort: 8081
              name: http